Silence gcc -Wunused-function
gcc on MacOS-ARM64  may error out with

/Users/runner/work/php-src/php-src/ext/hash/blake3/upstream_blake3/c/blake3_dispatch.c:112:5: error: unused function 'get_cpu_features' [-Werror,-Wunused-function]

full compiler log https://github.com/php/php-src/actions/runs/7762643678/job/21173438425?pr=13194

- the optimal fix would be to make sure get_cpu_features() is only compiled on platforms where it is used, but that would take more effort (have not investigated how much effort that would be)