add missing MAYBE_UNUSED
caused
```
/Users/runner/work/php-src/php-src/ext/hash/blake3/upstream_blake3/c/blake3_dispatch.c:237:26: error: unused variable 'features' [-Werror,-Wunused-variable]
  const enum cpu_feature features = get_cpu_features();
```